CREATE PROCEDURE [dbo].[usp_GETSCHEDULERINSTANCEDETAILS]
	@ID uniqueidentifier
AS
BEGIN
	SELECT INSTANCE.ID, INSTANCE.INSTANCENAME, SETTINGS.ISIMMEDIATEENGINESTARTENABLED, SETTINGS.ISJOBSDIRECTORYTRACKINGENABLED 
	FROM dbo.SCHEDULERINSTANCE AS INSTANCE
		LEFT JOIN dbo.SCHEDULERINSTANCESETTING AS SETTINGS on SETTINGS.INSTANCEID = INSTANCE.ID 
	WHERE INSTANCE.ID = @ID
END
