SET NOCOUNT ON

SET IDENTITY_INSERT [dbo].[SCHEDULERINSTANCESETTING] ON

MERGE INTO [dbo].[SCHEDULERINSTANCESETTING] AS Target
USING (VALUES
  (1,N'5AAF9FD7-5BC6-4C49-A7BD-182966A34D4C',0,1,NULL)
 ,(2,N'98C1A030-039D-4EE3-9CCA-640B5F47848A',1,1,N'E:\Development\Sources\Scheduler\src\Jobs')
) AS Source ([ID],[INSTANCEID],[ISIMMEDIATEENGINESTARTENABLED],[ISJOBSDIRECTORYTRACKINGENABLED],[JOBSDIRECTORYPATH])
ON (Target.[ID] = Source.[ID])
WHEN MATCHED AND (
	NULLIF(Source.[INSTANCEID], Target.[INSTANCEID]) IS NOT NULL OR NULLIF(Target.[INSTANCEID], Source.[INSTANCEID]) IS NOT NULL OR 
	NULLIF(Source.[ISIMMEDIATEENGINESTARTENABLED], Target.[ISIMMEDIATEENGINESTARTENABLED]) IS NOT NULL OR NULLIF(Target.[ISIMMEDIATEENGINESTARTENABLED], Source.[ISIMMEDIATEENGINESTARTENABLED]) IS NOT NULL OR 
	NULLIF(Source.[ISJOBSDIRECTORYTRACKINGENABLED], Target.[ISJOBSDIRECTORYTRACKINGENABLED]) IS NOT NULL OR NULLIF(Target.[ISJOBSDIRECTORYTRACKINGENABLED], Source.[ISJOBSDIRECTORYTRACKINGENABLED]) IS NOT NULL OR 
	NULLIF(Source.[JOBSDIRECTORYPATH], Target.[JOBSDIRECTORYPATH]) IS NOT NULL OR NULLIF(Target.[JOBSDIRECTORYPATH], Source.[JOBSDIRECTORYPATH]) IS NOT NULL) THEN
 UPDATE SET
  [INSTANCEID] = Source.[INSTANCEID], 
  [ISIMMEDIATEENGINESTARTENABLED] = Source.[ISIMMEDIATEENGINESTARTENABLED], 
  [ISJOBSDIRECTORYTRACKINGENABLED] = Source.[ISJOBSDIRECTORYTRACKINGENABLED], 
  [JOBSDIRECTORYPATH] = Source.[JOBSDIRECTORYPATH]
WHEN NOT MATCHED BY TARGET THEN
 INSERT([ID],[INSTANCEID],[ISIMMEDIATEENGINESTARTENABLED],[ISJOBSDIRECTORYTRACKINGENABLED],[JOBSDIRECTORYPATH])
 VALUES(Source.[ID],Source.[INSTANCEID],Source.[ISIMMEDIATEENGINESTARTENABLED],Source.[ISJOBSDIRECTORYTRACKINGENABLED],Source.[JOBSDIRECTORYPATH])
WHEN NOT MATCHED BY SOURCE THEN 
 DELETE
;
GO
DECLARE @mergeError int
 , @mergeCount int
SELECT @mergeError = @@ERROR, @mergeCount = @@ROWCOUNT
IF @mergeError != 0
 BEGIN
 PRINT 'ERROR OCCURRED IN MERGE FOR [dbo].[SCHEDULERINSTANCESETTING]. Rows affected: ' + CAST(@mergeCount AS VARCHAR(100)); -- SQL should always return zero rows affected
 END
ELSE
 BEGIN
 PRINT '[dbo].[SCHEDULERINSTANCESETTING] rows affected by MERGE: ' + CAST(@mergeCount AS VARCHAR(100));
 END
GO

SET IDENTITY_INSERT [dbo].[SCHEDULERINSTANCESETTING] OFF
GO
SET NOCOUNT OFF
GO