CREATE TABLE [dbo].[JOBDETAIL] (
    [ID]             INT                IDENTITY (1, 1) NOT NULL,
    [JOBNAME]        NVARCHAR (255)     NOT NULL,
    [JOBGROUP]       NVARCHAR (255)     NOT NULL,
    [JOBDESCRIPTION] NVARCHAR (MAX)     NULL,
    [JOBSCHEDULE]    NVARCHAR (100)     NULL,
    [JOBLASTRUNTIME] DATETIMEOFFSET (7) NULL,
    [JOBNEXTRUNTIME] DATETIMEOFFSET (7) NULL,
    [STATUSID]       TINYINT            NOT NULL,
    [INSTANCEID]     UNIQUEIDENTIFIER   NOT NULL,
    CONSTRAINT [PK_JOBDETAIL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_JOBDETAIL_SCHEDULERINSTANCE] FOREIGN KEY ([INSTANCEID]) REFERENCES [dbo].[SCHEDULERINSTANCE] ([ID]),
    CONSTRAINT [FK_JOBDETAIL_STATUS] FOREIGN KEY ([STATUSID]) REFERENCES [dbo].[JOBSTATUS] ([ID])
);

