CREATE TABLE [dbo].[SCHEDULERSTATUS] (
    [ID]         SMALLINT       IDENTITY (1, 1) NOT NULL,
    [STATUSNAME] NVARCHAR (100) NOT NULL,
    CONSTRAINT [PK_STATUSGROUP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

