CREATE TABLE [dbo].[SCHEDULERINSTANCESETTING] (
    [INSTANCEID] UNIQUEIDENTIFIER NOT NULL,
    [KEY]        NVARCHAR (150)   NOT NULL,
    [VALUE]      NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_SCHEDULERINSTANCESETTING] PRIMARY KEY CLUSTERED ([INSTANCEID] ASC, [KEY] ASC),
    CONSTRAINT [FK_SCHEDULERINSTANCESETTING_SCHEDULERINSTANCE] FOREIGN KEY ([INSTANCEID]) REFERENCES [dbo].[SCHEDULERINSTANCE] ([ID])
);



