CREATE TABLE [dbo].[SCHEDULERINSTANCESETTING] (
    [ID]                             INT              IDENTITY (1, 1) NOT NULL,
    [INSTANCEID]                     UNIQUEIDENTIFIER NOT NULL,
    [ISIMMEDIATEENGINESTARTENABLED]  BIT              CONSTRAINT [DF_SCHEDULERINSTANCESETTING_ISIMMEDIATEENGINESTARTENABLED] DEFAULT ((1)) NOT NULL,
    [ISJOBSDIRECTORYTRACKINGENABLED] BIT              CONSTRAINT [DF_SCHEDULERINSTANCESETTING_ISJOBSDIRECTORYTRACKINGENABLED] DEFAULT ((1)) NOT NULL,
    [JOBSDIRECTORYPATH]              NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_SCHEDULERINSTANCESETTING_1] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SCHEDULERINSTANCESETTING_SCHEDULERINSTANCE] FOREIGN KEY ([INSTANCEID]) REFERENCES [dbo].[SCHEDULERINSTANCE] ([ID])
);

