CREATE TABLE [dbo].[SCHEDULERINSTANCE] (
    [ID]           UNIQUEIDENTIFIER NOT NULL,
    [INSTANCENAME] NVARCHAR (255)   NOT NULL,
    CONSTRAINT [PK_SCHEDULERINSTANCE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

